@startuml

class Person {
  +name
  +email
  +location
}

class BookTaker {
}

class BookGiver {
}

class BookBox {
  +boxName
  +location : Location 
  isFull : boolean
}

class Location {
    latitude
    longitude
}

class Book {
  +title
  +authorName : string[1..*]
  +genre : string[1..*]
  +status
  +ISBN
}


class Donation {
  +donationDate
  +status
  +donateBookID
}

class Feedback {
  +reasonText
}


class ProblemReport {
  +description
  +status
  +reportTime
}

class MaintenanceTeam {
}

class Route {
  +startLocation
  +endLocation
  +directions : Path
  +estimatedTime
  +distance
}

class Path {

}

Person <|-- BookTaker
Person <|-- BookGiver


BookBox "1" o-- "0..*" Book : contains


Person --> Route : uses
Route --> BookBox
Person --> BookBox : navigates to

Donation --> Book : donates
BookGiver --> Donation : creates
Donation --> BookBox : toBox

BookTaker --> Feedback : provides
Feedback --> Book : about

Person --> ProblemReport : submits
ProblemReport --> BookBox : for
MaintenanceTeam --> ProblemReport : handled

@enduml
